# Generated by Django 4.2.10 on 2024-02-13 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name category', max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='name')),
                ('slug', models.SlugField(help_text='Link', max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='link')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'category',
            },
        ),
    ]
